apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-frontend-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-frontend-server
    spec:
      containers:
      - name: kube-frontend-server
        image: kube-frontend-server:0.1
        ports:
        - containerPort: 80