apiVersion: v1
kind: Service
metadata:
  name: kube-frontend-server
  labels:
    app: kube-frontend-server
spec:
  selector:
    app: kube-frontend-server
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30060
  type: LoadBalancer